cta:
  left:
    title: I want to buy this service
    description:  Do you like this product? Contact us to discuss your options.
    button: Find out more
  right:
    title: I want to become a member
    description: Do you like this product, and would you like to contribute to its direction?
    button: Find out more

users:
  title: Project users
  visitWebsite: Visit website
